### ISSUE TITLE
Duplicate events question

### ISSUE THREAD

**Issue by dlapin-cribl** [clhobbs/events-splitter#9]
I haven't really looked into db structure, but aren't `should not have duplicate agent or target events` and `agent event should not exist in both targets` are doing almost the same thing?

**Comment by clhobbs** [comment]
Test case 1: `should not have duplicate agent or target events` uses this SQL:
```
SELECT source, data, count(*) count FROM events GROUP BY source, data HAVING count(*) > 1
```
This will catch the problem where either:
- an agent event is duplicated, or
- 1 agent event exists multiple times in either Target file

Test case 2: `agent event should not exist in both targets` uses this SQL:
```
SELECT data FROM events WHERE source = 'Target1' INTERSECT SELECT data FROM events WHERE source = 'Target2'
```
This will catch the problem where 1 single Agent event is mistakenly copied to BOTH targets.  Basically, it's checking that Target1 and Target2 contain mutually exclusive sets of data.

An example:
Agent event "This is event number 999" -- the Splitter mistakenly adds this to Target1 file twice and does not add it to Target2 file at all --- in this case, the 1st test case will fail, but the 2nd will pass.

**Comment by dlapin-cribl** [comment]
Gotcha!
In this particular assignment we're more interested in finding duplicates across all of the targets, so if the event is present in target1 and also in target2 it is considered a duplicate. The way you implemented it is also correct but could be done in one test case. No need to re-implement though
